# Generated by Django 3.2.3 on 2021-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(help_text='Number of cylinders', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(help_text='Enter a description', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='hp',
            field=models.IntegerField(help_text='Horse Power', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='maxspeed',
            field=models.IntegerField(help_text='Max Speed', null=True),
        ),
    ]
